export enum ActionType {
  UPDATE_CELL = 'UPDATE_CELL',
  MOVE_CELL = 'MOVE_CELL',
  DELETE_CELL = 'DELETE_CELL',
  INSERT_CELL_AFTER = 'INSERT_CELL_AFTER',
  BUILD_START = 'BUILD_START',
  BUILD_DONE = 'BUILD_DONE',
  FETCH_CELLS = 'FETCH_CELLS',
  FETCH_CELLS_SUCCESS = 'FETCH_CELLS_SUCCESS',
  FETCH_CELLS_FAIL = 'FETCH_CELLS_FAIL',
}
